<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'TLC_Transient' => $vendorDir . '/markjaquith/wp-tlc-transients/class-tlc-transient.php',
    'TLC_Transient_Update_Server' => $vendorDir . '/markjaquith/wp-tlc-transients/class-tlc-transient-update-server.php',
);
